<?php

use Illuminate\Database\Seeder;
use App\Question;

use Faker\Factory as Factory;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            'Me gustan las revistas de mecánica',
            'Tengo buen apetito',
            'Despierto descansado(a) y fresco(a) casi todas las mañanas',
            'Creo que me gustaría el trabajo de bibliotecario',
            'El ruido me despierta fácilmente',
            'Mi padre es un hombre bueno, o (si su padre ha fallecido) fue un hombre bueno',
            'Me gusta leer los artículos sobre crímenes en los periódicos',
            'Por lo general tengo las manos y los pies lo suficientemente calientes',
            'Mi vida diaria está llena de cosas que mantienen mi interes',
            'Actualmente estoy tan capacitado(a) para trabajar como siempre lo he estado',
            'Siento un nudo en la garganta casi todo el tiempo',
            'Mi vida sexual es satisfactoria',
            'La gente debería tratar de comprender sus sueños y guiarse por ellos o considerarlos como advertencias',
            'Me gustan las novelas de detectives o de misterio',
            'Trabajo bajo una gran presión',
            'De vez en cuando pienso en cosas demasiado malas como para hablar de las',
            'Estoy seguro(a) que la vida es injusta conmigo',
            'Sufro ataques de nausea y de vómito',
            'Al iniciar un nuevo empleo me gusta saber con qué personas es importante ser amable',
            'Muy raras veces padezco estreñimiento',
            'A veces he sentido un intenso deseo de abandonar mi hogar',
            'Nadie parece comprenderme',
            'A veces me dan ataques de risa o de llanto, que no puedo controlar',
            'En ocasiones los espíritus malignos se posesionan de mi',
            'Me gustaría ser cantante',
            'Cuando estoy en problemas creo que lo mejor es quedarme callado(a)',
            'Por principio, cuando alguien me hace algun mal siento que, de ser posible, debería pagarle con la misma moneda',
            'Padezco acidez estomacal varias veces a la semana',
            'En ocasiones siento deseos de maldecir',
            'Tengo pesadillas varias veces a la semana',
            'Tengo dificultades para concentrarse en una tarea o trabajo',
            'He tenido experiencias muy peculiares y extrañas',
            'Raras veces me preocupo por mi salud',
            'Nunca he tenido dificultades a causa de mi conducta sexual',
            'Cuando era más joven, a veces robe algunas cosas',
            'Casi siempre tengo tos',
            'A veces siento ganas de destrozar las cosas',
            'He tenido periodos de dias, semanas o meses, en los que no podia hacer nada, porque no tenia la energia suficiente para empezar',
            'Mi sueño es irregular e intranquilo',
            'A menudo me parece que me duele toda la cabeza',
            'No siempre digo la verdad',
            'Si la gente no hubiera querido perjudicarme, hubiera tenido mas éxito en la vida',
            'Soy mas sensato ahora que nunca',
            'Una vez a la semana o mas a menudo, sin causa aparente siento calor en todo el cuerpo',
            'Estoy tan sano como la mayoria de mis amigos',
            'Prefiero hacerme el desentedido cuando veo a amigos de la escuela o a personas conocidad que no he visto por mucho tiempo, a no ser que ellas me hablen primero',
            'Casi nunca me ha dolido el corazon o el pecho',
            'Casi siempre prefirira soñar despierto en lugar de hacer otra cosa',
            'Soy una persona muy sociable',
            'Con frecuencia he tenido que recibir ordenes de personas que sabian menos que yo',
            'No leo diariamente todos los articulos del periodico',
            'No he llevado una vida correcta',
            'Con frecuencia me parece sentir ardores, punzadas, hormigueo o adormecimiento en algunas partes del cuerpo',
            'A mi familia no le gista el trabajo que escogi o la ocupacion que pienso escoger para trabajar el resto de mi vida',
            'Algunas veces me empeño tnto en algo que las personas pierden la paciencia conmigo',
            'Quisiera poder ser tan feliz como parecen serlo otras personas',
            'Muy rara veces siento dolor en la nuca',
            'Creo que muchas gente exagera sus desgracias para que los demas se compadezcan de ellos y les ayuden',
            'Sufro de malestares en la boca del estomago, varios dias a la semana o mas frecuentemete',
            'Cuando estoy con gente me molesta oir cosas muy extrañas',
            'Soy una persona importante',
            'A menudo he deseado ser mujer, (o si usted es mujer) nunca he lamentado ser mujer',
            'Las personas no lastiman mis sentimientos con facilidad',
            'Me gusta leer novelas de amor',
            'La mayor parte del tiempo me siento tristo',
            'Seria mejor que se desecharan casi todas las leyes',
            'Me gusta la poesia',
            'A veces molesto a los animales',
            'Creo que me gustaria trabajar como guardabosques',
            'Pierdo facilmente las discusiones',
            'En la actualidad me es dificil no perder la esperanza de llegar a ser alguien',
            'A veces mi alma abandona mi cuerpo',
            'Definitivamente no tengo confianza en mi mismo',
            'Me gustaria ser florista',
            'Generalmente siento que la vida vale la pena',
            'Cuesta mucho trabajo convencer a la mayoria de la gente de la verdad',
            'De vez en cuando dejo para mañana lo que deberia hacer hoy',
            'Le agrado a la mayoria parte de la gente que me conoce',
            'No me molesta que se burlen de mi',
            'Me gustaria ser enfermera (enfermero)',
            'Creo que la mayoria de la gente mentiria para salir adelante',
            'Hago muchas cosas de las que luego me arrepiento (Me arrepiento mas, o mas frecuentamente que otras personas, de las cosas que hago)',
            'Tengo pocos disgustos con miembros de mi familia',
            'Cuando joven me suspendieron de la escuela una o mas veces por mala conducta',
            'A veces siento un fuerte impulso de hacer algo dañino o escandaloso',
            'Me gusta ir a fiestas y reuniones animadas y alegres',
            'Me he enfrentado a problemas con tantas posibilidades de solucion que no he podido llegar a una decision',
            'Creo que la mujer debe tener tanta libertad sexual como el hombre',
            'Los conflictos mas graves que tengo son conmigo mismo',
            'Quiero a mi padre, (o si su padre ha fallecido) quise a mi padre',
            'Casi nunca tengo calambres o contracciones musculares',
            'No parece importante lo que me pase',
            'Algunas veces , cuando no me siento bien, soy irritable',
            'Muchas veces tengo la sensacion de haber hecho algo malo o diabolico',
            'Casi siempre estoy feliz',
            'A mi alrededor veo cosas, animales o personas que otros no ven',
            'Me parece tener la cabeza o la nariz congestionadas la mayor parte del tiempo',
            'Algunas personas son tan mandonas que siento el deseo de hacer lo contrario de lo que me piden, aunque sepa que tienen la razon',
            'Alguien tiene mala voluntad',
            'Nunca he hecho algo peligroso solo por el gusto de hacerlo',
            'A menudo siento como si tuviera una banda que me apretara la cabeza',
            'Algunas veces me enojo',
            'Disfruto mas de una carrera o de un juego cuando apuesto',
            'La mayor parte de la gente es honrada principalmente por temor a ser descubierta',
            'En la escuela algunas veces me llevaron ante el director por malas conductas',
            'Mi manera de hablar es la misma de siempre (ni mas rapida, ni mas lenta, ni balbuceante, ni roca)',
            'Mis modales en la mesa no son tan buenos en casa como cuando salgo a comer con otras personas',
            'Cualquier persona que sea capaz y este dispuesta a trabajar duro tiene buenas posibilidades de exito',
            'Me parece que soy tan listo (a) y capaz como la mayoria de los que me rodean',
            'La mayoria de la gente usaria medios discutibles con tal de obtener lo que quiere',
            'Tengo muchos problemas estomacales',
            'Me gusta el arte dramatico',
            'Se quien es el responsable de la mayoria de mis problemas',
            'Algunas veces me siente tan atraido (a) por las cosas personales de otros, como calzado, guantes, etc, que me gustaria tocarlos o robarlos aunque no me sirvan',
            'Cuando veo sangre no me asusto ni me enfermo',
            'Con frecuencia no puedo comprender por que he estado tan irritable y malhumorado (a)',
            'Nunca he vomitado ni escupido sangre',
            'No me preocupa contraer enfermedades',
            'Me gusta recoger flores o cultivar plantas dentro de mi casa',
            'Con frecuencia siento la necesidad de luchar por lo que creo junto',
            'Nunca me he entregado a practicas fuera de lo comun',
            'A veces mis pensamientos han pasado por mi mente con tanta rapidez que no he podido expresarlos en palabras',
            'Si pudiera entrar a un cine sin pagar y estuviera seguro (a) de no ser descubierto (a), probablemente lo haria',
            'A menudo me pregunto cual sera la verdadera intencion de las personas que hacen algo bueno para mi',
            'Creo que mi vida hogareña es tan agradable como la de la mayoria de las personas que conozco',
            'Creo en el cumplimiento de la ley',
            'La critica o el regaño me hieren profundamente',
            'Me gusta cocinar',
            'Mi conducta depende principalmente del comportamiento de las personas que me rodean',
            'Definitavamente, a veces me siento un inutil',
            'Cuando niño (a) pertenencia a un grupo de amigos que procurabamos ser leales en cualquier problema',
            'Creo que existe otra vida despues de esta',
            'Me gustaria ser soldado',
            'A veces siento el deseo de empezar una pelea a golpes con alguna persona',
            'Muchas veces he perdido oportunidades por no haber decidido a tiempo',
            'Me impacienta que la gente me pida consejos o me interrumpa cuando estoy trabajando en algo importante',
            'Acostumbra llevar un diario sobre mi vida',
            'Creo que estan conspirando contra mi',
            'Prefiero ganar que perder en un juego',
            'Casi todas las noches me quedo dormido (a) sin tener pensamientos o ideas que me preocupen',
            'Durante los ultimos años he gozado de buena salud la mayoria parte del tiempo',
            'Nunca he tenido un ataque de convulsiones',
            'No subo ni bajo de peso',
            'Creo que me estan siguiendo',
            'Siento que frecuentemente he sido castigado (a) sin motivo',
            'Lloro facilmente',
            'No entiendo lo que leo tan bien como antes',
            'Nunca en mi vida me he sentido mejor que ahora',
            'A veces la parte superior de mi cabeza esta muy sensibles',
            'Algunas veces siento que deberia herirme o lastimar a otros',
            'Me molesta que alguien me engañe tan habilmente que tenga que adminit que fui burlado (a)',
            'No me canso con facilidad',
            'Me gusta conocer gente importante porque eso me hace sentir importante',
            'Siento miedo cuando miro hacia abajo desde un lugar alto',
            'No me preocuparia si alguno de mis familiares tuviera problemas con la ley',
            'Solo estoy contento cuando paseo o viajo sin un plan definido',
            'No me importa lo que otros piensen de mi',
            'Me siento incomodo (a) cuando tengo que hacer payasadas en una reunion, aun cuando los demas esten haciendo lo mismo',
            'Nunca me he desmayado',
            'Me gustaba la escuela',
            'Frecuentemente tengo que esforzarme para no desmostrar que soy timido (a)',
            'Alguien ha intentado envenenarme',
            'No le tengo mucho miedo a las serpientes',
            'Nunca o casi nunca tengo mareos',
            'Mi memoria parece estar en buenas condiciones',
            'Me preocuopan las cuestiones sexuales',
            'Me cuenta trabajo entablar una conversacion con alguien que acabo de conocer',
            'He tenido epocas durante las cuales he hecho cosas que luego no recuerdo haber hecho',
            'Cuando me aburro me gusta provocar algo emocinante o divvertido',
            'Tengo miedo de perder el juicio',
            'Estoy en contra de dar dinero a los pordioseros',
            'Con frecuencia noto que mis manos tiemblan cuando trato de hacer algo',
            'Puedo ller durante mucho tiempo sin que se me cansen los ojos',
            'Me gusta leer o estudiar acerca de las cosas en las que estoy trabajando',
            'Siento debilidad general la mayor parte del tiempo',
            'Muy pocas veces me duele la cabeza',
            'Mis manos no se han entorpecido ni perdido habilidad',
            'Algunas veces cuando me apeno empiezo a sudar, cosa que me molesta muchisimo',
            'No he tenido dificultad en mantener el equilibrio cuando camino',
            'Algo anda mal en mi mente',
            'No me dan accesos de alergia o de asma',
            'He tenido ataques durante los cuales no podia controlar el habla o los movimientos, pero me daba cuenta de lo que ocurría a mi alrededor',
            'No me agradan todas las personas que conozco',
            'Muy pocas veces sueño despierto(a)',
            'Desearía no ser tan tímido(a)',
            'No tengo miedo de manejar dinero',
            'Si fuera periodista me gustaría mucho escribir sobre teatro',
            'Disfruto de distintas clases de juegos y diversiones',
            'Me gusta coquetear',
            'Mi familia me trata más como un(a) niño(a) que como un adulto',
            'Me gustaria ser periodista',
            'Mi madre es una buena mujer, (o si su madre ha fallecido) mi madre era una buena mujer',
            'Cuando camino tengo mucho cuidado de no pisar las rayas en las banquetas',
            'Nunca he tenido erupciones (ronchas, salpullido, etcétera) que me preocuparan',
            'En comparación con otros hogares, hay muy poco compañerismo y cariño en mi familia, Frecuentemente me encuentro preocupado(a) por algo',
            'Creo que me gusta el trabajo de contratista de obras',
            'Frecuentemente oigo voces sin saber de dónde vienen',
            'Me gusta la ciencia',
            'No se me dificulta pedir ayuda a mis amigos aun cuando no pueda devolverles el favor',
            'Me gusta mucho cazar',
            'A menudo mis padres se oponen a la clase de gente que frecuentaba',
            'En ocasiones me gusta el chisme',
            'Aparentemente oigo tan bien como la mayoría de las personas',
            'Algunos de mis familiares tienen hábitos que me molestan o irritan mucho',
            'A veces creo que puedo tomar decisiones con extraordinaria facilidad',
            'Me gustaria pertenecer a varios clubes o asociaciones',
            'Raras veces noto los latidos de mi corazón, y muy pocas veces me falta la respiración',
            'Me gusta hablar sobre temas sexuales',
            'Me gusta visitar lugares donde nunca he estado',
            'Se me inculcó un modo de vida basado en el deber, el cual he seguido desde entonces con mucho cuidado',
            'Algunas veces he sido un obstáculo para personas que quieren hacer algo, no porque eso fuera importante, sino por cuestión de principios',
            'Me enojo con facilidad, pero se me pasa pronto',
            'He sido bastante independiente y liberado(a) de la disciplina familiar',
            'Me preocupo mucho',
            'Alguien ha estado intentando robar',
            'Casi todos mis parientes están de acuerdo conmigo',
            'Tengo periodos de tanta intranquilidad que no puedo permanecer sentado(a) mucho tiempo',
            'He tenido decepciones amorosas',
            'Nunca me preocupa mi apariencia fisica',
            'Sueño frecuentemente cosas que es mejor mantener en secreto',
            'Se debe enseñar a los niños la información básica sobre el sexo',
            'No creo ser más nervioso(a) que la mayoría de Las personas',
            'Padezco poca o ninguna clase de dolores',
            'Mi forma de hacer las cosas tiende a ser malinterpretada por otros',
            'Algunas veces sin razón, aun cuando las cosas van mal, me siento muy alegre, como si estuviera en "la cima del mundo"',
            'No culpo a nadie por tratar de apoderarse de todo lo que pueda en este mundo',
            'Hay personas que quieren apoderarse de mis pensamientos e ideas',
            'He tenido momentos en los que mi mente se ha quedado en blanco y no me daba cuenta de lo que ocurría a mi alrededor',
            'Puedo ser amistoso(a) con personas que hacen cosas que considero incorrectas',
            'Me gusta estar en un grupo en el que se hacen bromas los unos los otros',
            'En las elecciones, algunas veces voto por candidatos que casi no conozco',
            'Se me dificulta comenzar a hacer las cosas',
            'Creo que estoy condenado(a)',
            'Fui una persona lenta para aprender en la escuela',
            'Si fuera artista me gustaria dibujar flores',
            'No me molesta no ser mejor parecido(a)',
            'Sudo con facilidad aun en días frescos',
            'Tengo entera confianza en mí mismo',
            'A veces me ha sido imposible evitar robar o llevarme algo de una tienda',
            'Es más seguro no confiar en nadie',
            'Una vez a la semana o más frecuentemente me pongo muy agitado(a)',
            'Cuando estoy con un grupo de personas se me dificulta pensar en temas apropiados para platicar o conversar',
            'Cuando me siento triste, casi siempre algo emocionante me saca de ese estado',
            'Cuando salgo de casa no me preocupo por cerrar bien las ventanas y la puerta con llave',
            'Creo que mis pecados son imperdonables',
            'Se me adormecen una o varias partes de la piel',
            'No culpo a la persona que se aprovecha de otra, si esta última se expone a que ocurra tal cosa',
            'Mi vista está tan bien ahora como lo ha estado por años',
            'A veces me divierte tanto la astucia de algún criminal, que he deseado que se salga con la suya',
            'Con frecuencia me ha parecido que algún extraño me miraba críticamente',
            'Todo me sabe igual',
            'Todos los días tomo una cantidad extraordinaria de agua',
            'La mayoría de las personas hace amistades porque los amigos les pueden resultar útiles en algún momento',
            'Casi nunca noto que me zumben o silben los oidos',
            'De vez en cuando siento odio hacia los miembros de mi familia a los que usualmente quiero',
            'Si fuera reportero(a) me gustaría mucho escribir notas deportivas',
            'Puedo dormir durante el dia pero no durante la noche',
            'Estoy seguro(a) de que la gente habla de mí',
            'A veces me río de los chistes obscenos',
            'Tengo muy pocos temores en comparación con los de mis amigos',
            'No me sentiría apenado(a) si ante un grupo de personas, tuviera que iniciar una discusión u opinar acerca de algo que conozco bien',
            'Siempre me molesta que la justicia deje libre a un criminal debido a las maniobras de un abogado astuto',
            'He bebido alcohol con exceso',
            'Por lo general no le hablo a la gente, hasta que ellos me hablan',
            'Nunca he tenido problemas con la ley',
            'Tengo periodos en que me siento muy alegre sin que exista una razón especial',
            'Quisiera que no me perturbaran pensamientos sexuales',
            'Si varias personas se hallan en apuros, lo mejor que pueden hacer es ponerse de acuerdo sobre lo que van a decir y mantenerse firmes en lo que acuerden',
            'No me molesta mucho ver sufrir a los animales',
            'Creo que siento más intensamente que la mayoría de las personas',
            'Nunca en mi vida me gustó jugar con muñecas',
            'A menudo la vida me resulta dificil',
            'Soy tan susceptible respecto a algunos temas que ni siquiera puedo hablar de ellos',
            'En la escuela me era muy dificil hablar frente a la clase',
            'Quiero a mi madre, (o si su madre ha fallecido) quise a mi madre',
            'Aun cuando estoy acompañado(a) me siento solo(a) la mayor parte del tiempo',
            'Recibo toda la comprensión que debiera recibir',
            'Me niego a participar en algunos juegos porque no los sé jugar bien',
            'Creo que hago amistades tan fácilmente como cualquiera',
            'No me gusta tener gente a mi alrededor',
            'Me han dicho que camino cuando estoy dormido(a)',
            'La persona que causa tentación dejando propiedades de valor sin protección, es tan culpable del robo como el ladrón mismo',
            'Creo que casi todo el mundo mentiria para evitar problemas',
            'Soy más sensible que la mayoría de la gente',
            'A la mayor parte de la gente le disgusta ayudar a los demás, aunque no lo diga',
            'Muchos de mis sueños están relacionados con el sexo',
            'Mis padres y familiares me encuentran más fallas de las que debieran',
            'Me avergüenzo muy fácilmente',
            'El dinero y los negocios me preocupan',
            'Nunca he estado enamorado(a) de alguien',
            'Algunos de mis familiares han hecho ciertas cosas que me han asustado',
            'Casi nunca sueño',
            'Cuadernillo de aplicación',
            'Con frecuencia me salen manchas rojas en el cuello',
            'Nunca he sufrido parálisis o alguna debilidad fuera de lo común en alguno de mis músculos',
            'Algunas veces pierdo o me cambia la voz, aunque no esté resfriado(a)',
            'Mi padre o mi madre frecuentemente me hacían obedecer, aun cuando yo creia que no tenian la razón',
            'A veces percibo olores raros',
            'No me puedo concentrar en una sola cosa',
            'Tengo motivos para sentir celoso(a) de uno o más miembros de mi familia',
            'Casi todo el tiempo me siento preocupado(a) por algo o por alguien',
            'Pierdo fácilmente la paciencia con la gente',
            'La mayor parte del tiempo desearía estar muerto(a)',
            'Algunas veces me siento tan inquieto(a) que me es dificil quedarse dormido(a)',
            'Sin duda he tenido más cosas de que preocuparme de las que me corresponden',
            'A nadie le importa mucho lo que le suceda a uno',
            'A veces me molesta oir tan bien',
            'Se me olvida muy pronto lo que me dicen',
            'Generalmente tengo que detenerme a pensar antes de hacer algo, aunque sea un asunto sin importancia',
            'Con frecuencia cruzo la calle para evitar encontrarme con alguien que veo venir',
            'Muchas veces siento como si las cosas no fueran reales',
            'La única parte interesante del periódico son las caricaturas de la sección cónica',
            'Tengo la costumbre de contar cosas sin importancia, como la cantidad de focos en los anuncios luminosos y cosas por el estilo',
            'No tengo enemigos que realmente quieran hacerme daño',
            'Generalmente no me fio de las personas que son un poco más amigables de lo que esperaba',
            'Tengo pensamientos extraños y poco comunes',
            'Me pongo nervioso(a) y preocupado(a) cuando tengo que salir de casa para hacer un viaje corto',
            'Por lo general espero tener éxito en lo que hago',
            'Oigo cosas extrañas cuando estoy solo(a)',
            'He tenido miedo de cosas o personas que sabia que no podían hacerme daño',
            'No temo entrar solo(a) a un salón donde hay gente reunida platicando',
            'Tengo miedo de usar cuchillos o cualquier otra cosa filosa o puntiaguda',
            'Algunas veces me gusta herir a las personas que quiero',
            'Puedo atemorizar fácilmente a la gente y a veces lo hago para divertirme',
            'Es más dificil para mi concentrarme de lo que parece ser para otras personas',
            'En varias ocasiones he dejado de hacer algo porque he dudado de mi habilidad',
            'A menudo me vienen a la mente malas palabras, palabras horribles y me es imposible librarse de ellas',
            'Algunas veces me vienen a la mente pensamientos sin importancia que me molestan por días',
            'Casi todos los días sucede algo que me asusta',
            'A veces me siento lleno(a) de energia',
            'Tengo la tendencia a tomar las cosas muy en serio',
            'A veces he sentido placer cuando un ser querido me ha lastimado',
            'La gente dice cosas ofensivas y vulgares acerca de mi',
            'Me siento incómodo(a) cuando estoy en lugares cerrados',
            'Generalmente no me preocupo mucho de cómo soy y de cómo hago las cosas',
            'Alguien controla mi mente',
            'En las reuniones sociales o fiestas es más probable que me siente solo(a) o con una sola persona en vez de reunirme con el grupo',
            'La gente me desilusiona con frecuencia',
            'Algunas veces he sentido que las dificultades se acumulan de tal modo que no puedo vencerlas',
            'Me gusta muchisimo ir a bailes',
            'Durante ciertos periodos mi mente parece trabajar más lentamente que de costumbre',
            'A menudo platico con extraños en trenes, autobuses, etc',
            'Me gustan los niños',
            'Me gusta apostar cuando se trata de poco dinero',
            'Si me dieran la oportunidad, podria hacer algunas cosas que serían de gran beneficio para la humanidad',
            'Con frecuencia he conocido a personas supuestamente expertas y que no resultaron mejores que yo',
            'Me siento un(a) fracasado(a) cuando oigo hablar del éxito de alguien a quien conozco bien',
            'Pienso frecuentemente: "quisiera volver a ser nito(a)"',
            'Nunca me siento más contento(a) que cuando estoy solo(a)',
            'Si me dieran la oportunidad seria un(a) buen(a) líder',
            'Me siento incómodo(a) con los chistes obscenos',
            'Las personas generalmente exigen más respeto para sus propios derechos, que el que están dispuestas a conceder a los demás',
            'Me gustan las reuniones sociales sólo por estar con la gente',
            'Procuro recordar anécdotas interesantes para contarlas después a otras personas',
            'Una o más veces en mi vida he sentido que alguien me obligaba a hacer cosas hipnotizándome',
            'Cuando inicio una tarea me es dificil hacerla a un lado, aunque sea por un momento',
            'Con frecuencia no me entero de los chismes y habladurias de mi grupo',
            'A menudo me he encontrado personas que envidian mis buenas ideas, sólo porque a ellas no se les ocurrieron primero',
            'Disfruto con el alboroto de una multitud',
            'No me molesta conocer a personas extrañas',
            'Alguien ha tratado de influir en mi mente',
            'Recuerdo haberme fingido enfermo(a) para evitar algo',
            'Mis preocupaciones parecen desaparecer cuando estoy con un grupo de amigos(as) animados(as)',
            'Me rindo fácilmente cuando las cosas van mal',
            'Me gusta hacerle saber a la gente mi punto de vista sobre las cosas',
            'He tenido épocas en las que me sentía tan lleno(a) de energia que en ocasiones, hasta por varios dias, no necesitaba dormir',
            'Siempre que me es posible evito estar entre mucha gente',
            'Me atemorizo ante las crisis o dificultades',
            'Tiendo a dejar de hacer algo que quiero, si otros creen que eso no vale la pena',
            'Me Gustan las fiestas y las reuniones sociales',
            'He deseado frecuentemente ser una persona del sexo opuesto',
            'No me enojo fácilmente',
            'En el pasado he hecho cosas malas que nunca he contado a nadie',
            'La mayoría de las personas utilizaria medios, de alguna manera discutibles, para mejorar su situación en la vida',
            'Me pongo nervioso(a) cuando me preguntan cosas personales',
            'No me siento capaz de planear mi futuro',
            'No estoy contento(a) con mi manera de ser',
            'Me enojo cuando mi familia o amigos me aconsejan sobre cómo vivir mi vida',
            'Cuando era niño(a) me golpearon muchas veces',
            'Me siento incómodo(a) cuando la gente me halaga',
            'No me gusta escuchar a otras personas dar sus opiniones sobre la vida',
            'Con frecuencia tengo serios desacuerdos con personas importantes para mi',
            'Cuando las cosas van muy mal, sé que puedo contar con la ayuda de mi familia',
            'Me gustaba jugar a "la casita" cuando era pequeño(a)',
            'No le temo al fuego',
            'A veces me he alejado de alguna persona porque temia hacer o decir algo que pudiera lamentar después',
            'Solamente puedo expresar lo que en verdad siento, cuando tomo',
            'Muy rara vez me siento deprimido(a)',
            'Me han dicho con frecuencia que tengo mal genio',
            'Quisiera dejar de preocuparme por las cosas que he dicho y que quizás hayan herido los sentimientos de otras personas',
            'Me siento incapaz de contarle a alguien todo acerca de mí',
            'Temo a los relámpagos',
            'Me gusta tener a los demás intrigados con respecta a lo que haré',
            'Con frecuencia me ha parecido encontrar tantos obstáculos en mis planes que he tenido que abandonarlos',
            'Me da miedo estar solo(a) en la oscuridad',
            'A veces me he sentido muy mal al no ser comprendido(a) cuando trataba de evitar que alguien cometiera un error',
            'Le tengo terror a los huracanes',
            'Frecuentemente le pido consejo a la gente',
            'El futuro es demasiado incierto para que una persona haga planes serios',
            'Con frecuencia, aun cuando todo vaya bien, siento que nada me importa',
            'No le temo al agua',
            'Frecuentemente tengo que consultar con la almohada antes de tomar decisiones',
            'Con frecuencia la gente ha interpretado mal mis intenciones cuando trataba de corregir algo y ayudar',
            'No tengo dificultades al tragar',
            'Por lo general soy tranquilo(a) y no me altero fácilmente',
            'Me gustaría mucho ganarles a los criminales en su propio juego',
            'Merezco un severo castigo por mis pecados',
            'Tiendo a tomar los desengaños tan a pecho que no puedo dejar de pensar en ellos',
            'Me molesta que alguien me observa cuando trabajo, aun cuando sé que puedo hacerlo bien',
            'A menudo me molesta tanto cuando alguien trata de meterse en la fila, que le llamo la atención',
            'A veces pienso que no sirvo para nada',
            'Cuando era chico(a) frecuentemente no iba a la escuela aunque debía haberlo hecho',
            'Tengo uno o varios familiares que son muy nerviosos',
            'A veces he tenido que ser rudo(a) con personas groseras o inoportunas',
            'Me Preocupo mucho por posibles desgracias',
            'Tengo opiniones políticas bien definidas',
            'Me gustaría ser corredor(a) de autos',
            'Es correcto tratar de evitar el cumplimiento de la ley, siempre que ésta no se viole',
            'Hay ciertas personas que me desagradan tanto, que me alegro interiormente cuando están pagando las consecuencias por algo que han hecho',
            'Me pone nervioso(a) tener que esperar',
            'Tiendo a dejar de hacer algo que deseo cuandolos demás piensan que esa no es la manera correcta de hacerlo',
            'Me gustaba lo emocionante cuando era joven (o en mi niñez)',
            'Con frecuencia me esfuerzo para superar a alguien que me ha llevado la contraria',
            'Me molesta que la gente me mire en la calle, en las tiendas, etc',
            'El hombre que más se ocupó de mí cuando era niño(a) (mi padre, padrastro, etc) fue muy estricto conmigo',
            'Me gustaba brincar al avión y la cuerda',
            'Nunca he tenido una visión',
            'Varias veces he cambiado de modo de pensar acerca de mi trabajo',
            'Excepto por orden del médico, nunca he tomado drogas o pastillas para dormir',
            'Frecuentemente me siento apenado(a) por ser tan irritable y gruñón(a)',
            'En la escuela mis calificaciones en conducta generalmente eran malas',
            'Me fascina el fuego',
            'Cuando estoy en una situación dificil digo sólo aquella parte de la verdad que no me perjudica',
            'Si me hallara en dificultades junto con varios amigos que fueran tan culpables como yo, preferiría echarme toda la culpa antes que descubrirlos',
            'Con frecuencia le tengo miedo a la oscuridad',
            'Cuando un hombre está con una mujer, generalmente está pensando en cosas relacionadas con el sexo',
            'Generalmente le hablo claro a la gente a quien estoy tratando de mejorar o corregir',
            'Me produce terror la idea de un terremoto',
            'Me convierto rápidamente en partidario de una buena idea',
            'Generalmente hago las cosas por mi mismo(a), en vez de buscar a alguien que me enseñe a hacerlas',
            'Temo encontrarme encerrado(a) en un ropero o en un lugar pequeño y cerrado',
            'Tengo que admitir que a veces me he preocupado más de la cuenta por cosas que no valían la pena',
            'No trato de encubrir la mala opinión o lástima que me inspira una persona para que ésta desconozca lo que siento',
            'Soy una persona muy tensa',
            'Frecuentemente he trabajado para personas que se atribuyen el reconocimiento por un buen trabajo pero culpan a los subalternos de los errores',
            'A veces me es dificil defender mis derechos porque soy muy reservado(a)',
            'La suciedad me molesta o me horroriza:',
            'Vivo una vida de ensueños acerca de la cual no le digo nada a nadie',
            'Algunos de mis familiares se enojan fácilmente',
            'No puedo hacer nada bien',
            'A menudo me he sentido culpable porque he fingido mayor pesar del que realmente sentia,',
            'Generalmente defiendo con tenacidad mis propias opiniones',
            'No le temo a las arañas',
            'Me parece tener un porvenir sin esperanzas',
            'Los miembros de mi familia y mis parientes más cercanos se llevan bastante bien',
            'Me gustaria vestir ropa cara',
            'La gente puede hacerme cambiar de opinión muy fácilmente, aun cuando ya haya tomado una decisión',
            'Ciertos animales me ponen nervioso(a)',
            'Puedo soportar tanto dolor como cualquiera',
            ': Varias veces he sido el (la) último(a) en darme por vencido(a) al tratar de hacer algo',
            'Me molesta que la gente me apresure',
            'No le tengo miedo a los ratones',
            'Varias veces por semana siento como si algo terrible fuera a suceder',
            'Gran parte del tiempo me siento cansado(a)',
            'Me gusta reparar las cerraduras de las puertas',
            'Algunas veces estoy seguro(a) que los demás pueden saber lo que estoy pensando',
            'Me gusta leer libros sobre ciencia',
            'Tengo miedo de estar solo(a) en un sitio al descubierto',
            'Algunas veces me siento al borde una crisis nerviosa',
            'Un gran número de personas son culpables de mala conducta sexual',
            'Con frecuencia he tenido miedo durante la noche',
            'Me molesta que se me olvide dónde pongo las cosas',
            'La persona hacia la que sentía mayor afecto y admiración cuando era niño(a) fue una mujer (madre, hermana, tía u otra mujer)',
            'Me gustan más las novelas de aventuras que las de amor',
            'Con frecuencia me confundo y se me olvida lo que quiero decir',
            'Soy torpe y poco hábil',
            'Me gusta mucho jugar deportes rudos (como fútbol americano o fútbol soccer)',
            'Odio a toda mi familia',
            'Algunas personas piensan que soy una persona dificil de llegar a conocer',
            'La mayoría de mi tiempo libre lo paso a solas',
            'Cuando alguien hace algo que me enoja, le digo a la persona cómo me siento',
            'En general tengo problemas para decidir qué debo hacer',
            'La gente piensa que no soy atractivo(a)',
            'La gente no es muy amable conmigo',
            'Con frecuencia siento que no soy tan bueno(a) como otras personas',
            'Soy muy terco(a)',
            'He disfrutado fumando marihuana',
            'La enfermedad mental es señal de debilidad',
            'Tengo problemas con el alcohol o las drogas',
            'Los fantasmas o los espíritus pueden influir en las personas para bien o para mal',
            'Me siento incapaz cuando tengo que tomar una decisión importante',
            'Procuro siempre ser amable, aun cuando las demás personas estén molestas o sean criticonas',
            'Encuentro alivio cuando comparto mis problemas con alguien',
            'Los objetivos más importantes de mi vida están a mi alcance',
            'Creo que las personas deberian guardar sus problemas personales para sí mismas',
            'Actualmente no me siento estresado(a)',
            'Me molesta mucho pensar en hacer cambios en mi vida',
            'Mis mayores problemas se deben al comportamiento de alguien cercano a mi',
            'Odio ir al doctor, aun cuando estoy enfermo(a)',
            'Aunque no estoy satisfecho(a) con mi vida, nada puedo hacer ahora para cambiarla',
            'Hablar con alguien sobre los problemas y preocupaciones es mucho mejor que tomar drogas o medicinas',
            'Tengo algunos hábitos que son realmente dañinos',
            'Cuando los problemas necesitan solución, generalmente dejo que otra persona los resuelva',
            'Reconozco que tengo varios defectos que no seré capaz de cambiar',
            'Estoy tan harto(a) de lo que hago diariamente, que lo único que deseo es deshacerme de todo',
            'Recientemente he pensado en matarme',
            'Con frecuencia me irrita mucho que me interrumpan cuando estoy trabajando',
            'Frecuentemente siento que puedo leer la mente de otras personas',
            'Me pongo nervioso(a) cuando tengo que tomar decisiones importantes',
            'Algunas personas dicen que como demasiado aprisa',
            'Me drogo o me emborracho por lo menos una vez a la semana',
            'He sufrido una pérdida importante en mi vida, de la que nunca podré recuperarme',
            'En ocasiones me molesto y enojo tanto, que no sé qué me pasa',
            'Cuando alguien me pide que haga algo por ellos, me cuesta mucho trabajo decirles que no',
            'Nunca me siento más feliz que cuando estoy solo(a)',
            'Mi vida está vacía y sin significado',
            'Tengo dificultades para mantener un trabajo estable',
            'He cometido bastantes errores graves en mi vida',
            'Me enojo conmigo mismo(a) cuando accedo demasiado a los deseos de los demás',
            'Ultimamente he pensado mucho en matarme',
            'Me gusta tomar decisiones y asignar trabajo a otros',
            'Aun sin mi familia sé que siempre habrá alguien que me cuide',
            'Me molesta muchortener que esperar en fila para entrar a restaurantes, cines o eventos deportivos',
            'Nadie lo sabe, pero he tratado de matarme',
            'Todo pasa demasiado rápido a mi alrededor',
            'Sé que soy una carga para otros',
            'Después de un mal día, generalmente necesito algunos tragos para relajarme',
            'Muchos de los problemas que tengo se deben a la mala suerte',
            'A veces me parece que no puedo dejar de hablar',
            'Me he llegado a lastimar o cortar a mi mismo sin saber por qué',
            'Trabajo de más, aun cuando no me lo exigen',
            'Generalmente me siento mejor después de haber llorado',
            'Olvido dónde dejo las cosas',
            'Si pudiera vivir mi vida de nuevo no la cambiaría demasiado',
            'Me enojo mucho cuando la gente de la que dependo no tiene el trabajo listo a tiempo',
            'Si me enojo, sé con seguridad que me dará dolor de cabeza',
            'Me gusta negociar en situaciones dificiles',
            'La mayoría de los hombres son infieles a sus esposas de vez en cuando',
            'Últimamente he perdido la voluntad de resolver mis problemas',
            'Cuando he estado tomado(a) me he enojado y he roto muebles y platos',
            'Trabajo mejor cuando tengo un plazo fijo que cumplir',
            'Me he enojado tanto con alguien, que he sentido como si fuera a explotar',
            'Algunas veces he tenido pensamientos terribles acerca de mi familia',
            'Algunas personas me dicen que tengo problemas con el alcohol pero no estoy de acuerdo con ellos',
            'Siempre tengo muy poco tiempo para terminar lo que hago',
            'Ultimamente, mis pensamientos están más y más relacionados con la muerte y con la vida después de la muerte',
            'Frecuentemente guardo y almaceno cosas que probablemente nunca utilizaré',
            'Me he llegado a sentir tan enojado(a) que he lastimado a otra persona en un pleito a puñetazos',
            'Ultimamente siento que me están evaluando en todo lo que hago',
            'Actualmente tengo muy poca relación con mis parientes',
            'En ocasiones me parece escuchar lo que pienso en voz alta',
            'Cuando estoy triste, me ayuda a sentirme mejor visitar a los amigos',
            'Mucho de lo que me pasa ahora parece haberme sucedido con anterioridad',
            'Cuando la vida se pone dificil, quisiera tan sólo rendirme',
            'No puedo entrar sola) en un cuarto oscuro, aun en mi propia casa',
            'Me preocupa bastante el dinero',
            'El hombre debería ser el jefe de la familia',
            'El único lugar donde me siento tranquilo(a) es en mi casa',
            'Las personas con las que trabajo no comprenden mis problemas',
            'Estoy satisfecho(a) con la cantidad de dinero que gano',
            'Generalmente tengo la suficiente energia para hacer mi trabajo',
            'Es dificil para mi aceptar cumplidos',
            'En la mayoría de los matrimonios uno o los dos miembros de la pareja son infelices',
            'Casi nunca pierdo el control de mi mismo(a)',
            'Últimamente me cuesta mucho trabajo recordar lo que la gente me ha dicho',
            'Cuando estoy triste o deprimido(a), no desempeño mi trabajo como debiera',
            'La mayoría de las parejas casadas no se demuestran mucho afecto'
        ];


        foreach ($data as $d) {
            $q = new Question();
            $q->question = $d;
            $q->save();
        }
    }
}
